Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls')),   
    path('inventory/', include('base.urls')),
    path('invoice', include('invoice.urls')),
    path('inventory/login' , include('invoice.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inventory_list', views.inventory_list, name='inventory_list'),
    path('per_product/<int:pk>', views.per_product, name='per_product'),
    path('add_product/', views.add_products, name='add_product'),
    path('', views.dashboard, name='dashboard'),
]

invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, view_PDF, generate_PDF

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    #path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('invoice_pdf/<id>',generate_PDF, name='invoice_pdf')
]

base/forms.py
from django.forms import ModelForm
from .models import Product

from django import forms

from .models import Product, Supplier


class SupplierForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'name',
        'data-val': 'true',
        'data-val-required': 'Please enter name',
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'address',
        'data-val': 'true',
        'data-val-required': 'Please enter address',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'email',
        'data-val': 'true',
        'data-val-required': 'Please enter email',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'username',
        'data-val': 'true',
        'data-val-required': 'Please enter username',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'password',
        'data-val': 'true',
        'data-val-required': 'Please enter password',
    }))
    retype_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'retype_password',
        'data-val': 'true',
        'data-val-required': 'Please enter retype_password',
    }))

class AddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'sales', 'buying_price','cost_per_item', 'quantity_in_stock', 'quantity_sold']

invoice/forms.py
from django import forms
from django.forms import formset_factory
from .models import Invoice
class InvoiceForm(forms.Form):
    
        # fields = ['customer', 'message']
    customer = forms.CharField(
        label='Cusomter',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Customer/Company Name',
            'rows':1
        })
    )
    customer_email = forms.CharField(
        label='Customer Email',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'customer@company.com',
            'rows':1
        })
    )
    billing_address = forms.CharField(
        label='Billing Address',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '',
            'rows':1
        })
    )
    message = forms.CharField(
        label='Message/Note',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'message',
            'rows':1
        })
    )

class LineItemForm(forms.Form):
    
    service = forms.CharField(
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Service Name'
        })
    )
    description = forms.CharField(
        label='Description',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Enter Book Name here',
            "rows":1
        })
    )
    quantity = forms.IntegerField(
        label='Qty',
        widget=forms.TextInput(attrs={
            'class': 'form-control input quantity',
            'placeholder': 'Quantity'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        label='Rate $',
        widget=forms.TextInput(attrs={
            'class': 'form-control input rate',
            'placeholder': 'Rate'
        })
    )
    # amount = forms.DecimalField(
    #     disabled = True,
    #     label='Amount $',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control input',
    #     })
    # )
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

base/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Supplier, Product
from django.contrib.auth.decorators import login_required
from .forms import SupplierForm, AddProductForm
from django_pandas.io import read_frame
import plotly
import plotly.express as px
import json


# Create your views here.
def inventory_list(request):
    inventories = Product.objects.all()
    df = read_frame(inventories)

    product_in_stock = df.groupby(by="name").sum().sort_values(by="quantity_in_stock")
    product_in_stock = px.pie(product_in_stock, names=product_in_stock.index, values=product_in_stock.quantity_in_stock,
                              title="Product in Stock")
    product_in_stock = json.dumps(product_in_stock, cls=plotly.utils.PlotlyJSONEncoder)
    context = {
        "inventories":inventories,
        "product_in_stock": product_in_stock
    }
    return render(request, 'base/inventory_list.html', context)

@login_required
def per_product(request, pk):
    inventory = get_object_or_404(Product, pk=pk)
    context = {
        'inventory':inventory
    }
    return render(request, 'base/inventory_product.html', context)


from django.views.generic import ListView
from django.contrib.auth.decorators import login_required


# Supplier views
@login_required(login_url='login')
def create_supplier(request):
    forms = SupplierForm()
    if request.method == 'POST':
        forms = SupplierForm(request.POST)
        if forms.is_valid():
            name = forms.cleaned_data['name']
            address = forms.cleaned_data['address']
            email = forms.cleaned_data['email']
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            retype_password = forms.cleaned_data['retype_password']
            if password == retype_password:
                user = User.objects.create_user(username=username, password=password, email=email, is_supplier=True)
                Supplier.objects.create(user=user, name=name, address=address)
                return redirect('supplier-list')
    context = {
        'form': forms
    }
    return render(request, 'store/addSupplier.html', context)


def add_products(request):
    inventories = Product.objects.all()
    inventory_count = inventories.count()
    inventory_quantity = Product.objects.filter(name='')
    if request.method == 'POST':
        form = AddProductForm(request.POST)
        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get('name')
            messages.success(request, f'{product_name} has been added')
            return redirect('dashboard')
    else:
        form = AddProductForm()
    context = {
        'inventories': inventories,
        'form': form,
        'inventory_count': inventory_count,
    }
    return render(request, 'base/inventory_add.html', context)


def dashboard(request):
    inventories = Product.objects.all()
    df = read_frame(inventories)
    
    sales_graph = df.groupby(by="last_sales_date", as_index= False, sort= False)['sales'].sum()
    sales_graph = px.line(sales_graph, x= sales_graph.last_sales_date, y= sales_graph.sales, title="Sales Trend")
    sales_graph = json.dumps(sales_graph, cls= plotly.utils.PlotlyJSONEncoder)
    
    best_perfoming_product = df.groupby(by="name").sum().sort_values(by="quantity_sold")
    best_perfoming_product = px.bar(best_perfoming_product, x=best_perfoming_product.index, y=best_perfoming_product.quantity_sold, title="Best Performing Product")
    best_perfoming_product = json.dumps(best_perfoming_product, cls= plotly.utils.PlotlyJSONEncoder)
    
    product_in_stock = df.groupby(by="name").sum().sort_values(by="quantity_in_stock")
    product_in_stock = px.pie(product_in_stock, names=product_in_stock.index, values=product_in_stock.quantity_in_stock, title="Product in Stock")
    product_in_stock = json.dumps(product_in_stock, cls= plotly.utils.PlotlyJSONEncoder)

    
    
    context = {
        "inventories":inventories,
        "sales_graph":sales_graph,
        "best_perfoming_product":best_perfoming_product,
        "product_in_stock":product_in_stock
    }
    return render(request, "base/dashboard.html", context)

class ProductListView(ListView):
    model = Product
    template_name = 'store/product_list.html'
    context_object_name = 'product'

invoice/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse, FileResponse
from django.views import View
from xhtml2pdf import pisa

import invoice
from Eshop import settings
from .models import LineItem, Invoice
from .forms import LineItemFormset, InvoiceForm
import pdfkit
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

from .utils import render_to_pdf


class InvoiceListView(View):
    def get(self, *args, **kwargs):
        invoices = Invoice.objects.all()

        context = {
            "invoices":invoices,
        }
        return render(self.request, 'invoice/invoice-list.html', context)
    
    def post(self, request):        
        # import pdb;pdb.set_trace()
        invoice_ids = request.POST.getlist("invoice_id")
        invoice_ids = list(map(int, invoice_ids))

        update_status_for_invoices = int(request.POST['status'])
        invoices = Invoice.objects.filter(id__in=invoice_ids)
        # import pdb;pdb.set_trace()
        if update_status_for_invoices == 0:
            invoices.update(status=False)
        else:
            invoices.update(status=True)

        return redirect('invoice:invoice-list')


def createInvoice(request):
    """
    Invoice Generator page it will have Functionality to create new invoices, 
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LineItemFormset(request.GET or None)
        form = InvoiceForm(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset(request.POST)
        form = InvoiceForm(request.POST)

        if form.is_valid():
            invoice = Invoice.objects.create(customer=form.data["customer"],
                                             customer_email=form.data["customer_email"],
                                             billing_address=form.data["billing_address"],
                                             date=form.data["date"],
                                             due_date=form.data["due_date"],
                                             message=form.data["message"],
                                             )
            # invoice.save()

        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0
            for form in formset:
                service = form.cleaned_data.get('service')
                description = form.cleaned_data.get('description')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')
                if service and description and quantity and rate:
                    amount = float(rate) * float(quantity)
                    total += amount
                    LineItem(customer=invoice,
                             service=service,
                             description=description,
                             quantity=quantity,
                             rate=rate,
                             amount=amount).save()
            invoice.total_amount = total
            invoice.save()
            try:
                print("helo")#generate_PDF(request, id=invoice.id)
            except Exception as e:
                print(f"********{e}********")
            return redirect('dashboard')
    context = {
        "title": "Invoice Generator",
        "formset": formset,
        "form": form,
    }
    return render(request, 'invoice/invoice-create.html', context)


def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "Rochad Enterprises",
            "address" :"P.o Box 101, Nairobi, Ruai, Kenya",
            "phone": "0795002100",
            "email": "rochadenterprises@gmail.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        "due_date": invoice.due_date,
        "billing_address": invoice.billing_address,
        "message": invoice.message,
        "lineitem": lineitem,

    }
    return render(request, 'invoice/pdf_template.html', context)

from django.template.loader import get_template
from django.template import Context


from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa
import io

from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa

def generate_PDF(request, id=id):
    invoice = get_object_or_404(Invoice, id=id)
    line_items = invoice.lineitem_set.all()
    template = get_template('invoice/pdf_template.html')
    context = {
        "company": {
            "name": "Rochad Enterprises",
            "address": "P.o Box 101, Nairobi, Ruai, Kenya",
            "phone": "0795002100",
            "email": "rochadenterprises@gmail.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        "due_date": invoice.due_date,
        "billing_address": invoice.billing_address,
        "message": invoice.message,
        "line_items": line_items,
    }
    html = template.render(context)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'

    pisa.CreatePDF(html, dest=response)

    return response

def change_status(request):
    return redirect('invoice:invoice-list')

def view_404(request,  *args, **kwargs):

    return redirect('invoice:invoice-list')

#def upload_product_from_excel(request):
    # Upload excel file to static folder "excel"
    # add all product to database
    # save product to database
    # redirect to view_product
    #excelForm = excelUploadForm(request.POST or None, request.FILES or None)
    #print("Reached HERE!")
    #if request.method == "POST":
        #print("Reached HERE2222!")

        #handle_file_upload(request.FILES["excel_file"])
        #excel_file = "static/excel/masterfile.xlsx"
        #df = pd.read_excel(excel_file)
        #Product.objects.all().delete()
        #for index, row in df.iterrows():
            #product = Product(
                #product_name=row["product_name"],
                #product_price=row["product_price"],
                #product_unit=row["product_unit"],
            #)
            #print(product)
            #product.save()
        #return redirect("view_product")
    #return render(request, "invoice/upload_products.html", {"excelForm": excelForm})

invoice/templates/invoice/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'invoice1/css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'invoice1/js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     {% block custom_css %}{% endblock %}
    <title>Invoice Management</title>
</head>
<body>
     
    <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    <footer class="footer">
        <center><p class="has-text-weight-bold">Made with love  by Elvis Njaramba</p>
        </center>
        </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

invoice/templates/invoice/dashboard.html
{% extends 'base/layout.html' %}
{% block content  %}

<div class="content-section">
    <div class="row mx-auto justify-content-center">
        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart1"></div>
            </div>
        </div>

        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart2"></div>
            </div>
        </div>
        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart3"></div>
            </div>
        </div>


    </div>
</div>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script type="text/javascript">
    var graph1 = {{ sales_graph|safe }}
    Plotly.plot("chart1", graph1, {})

    var graph2 = {{ best_perfoming_product|safe }}
    Plotly.plot("chart2", graph2, {})

    var graph3 = {{ product_in_stock|safe }}
    Plotly.plot("chart3", graph3, {})
</script>
{% endblock %}

invoice/templates/invoice/invoice-create.html
{% extends "invoice/base.html" %}
{% load bulma_tags %}
{% block content %}
{% load static %}
<br>
<section class="hero is-fullheight">
    <div class="container">
        <div class="card white-ter">
            <div class="hero-body">
                <form class="" method="POST" action="">{% csrf_token %}
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.customer|bulma}}
                        </div>

                        <div class="column is-one-third">
                            {{form.customer_email|bulma}}
                        </div>
                        <div class="column is-one-third">
                            {{form.message|bulma}}
                        </div>
                    </div>
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            {{form.billing_address|bulma}}
                        </div>
                        <div class="column is-one-third">
                            date: <input class="input" type="date" name="date">
                        </div>
                        <div class="column is-one-third">
                            due-date: <input class="input" type="date" name="due_date">
                        </div>
                    </div>


                    <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                        <tbody>
                            <thead>
                                <tr>
                                    <th>Product/Service</th>
                                    <th>Description</th>
                                    <th>QTY</th>
                                    <th>RATE</th>
                                    <th>AMOUNT$</th>
                                    <th>ADD</th>
                                </tr>
                                {{ formset.management_form }}
                                {% for form in formset %}
                                <tr>
                                    <td>{{form.service}}</td>
                                    <td>{{form.description}}</td>
                                    <td>{{form.quantity}}</td>
                                    <td>{{form.rate}}</td>
                                    <td class="amount"></td>
                                    <td>
                                        <div class="input-group-append">
                                            <button
                                                class="button is-small btn btn-success add-form-row">+</button>&nbsp;
                                            <!-- <button class="button is-small btn btn-warning remove-form-row">-</button> -->
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </thead>
                        </tbody>

                    </table>
                    <div class="row spacer">
                        <div class="col-4 offset-2">
                            <button type="submit" class="button btn btn-block is-info is-half">Create</button>
                        </div>
                    </div>
                    <br>
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-4">Total($): <span id="total"></span></h3>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('table input').on("input", function () {
        var total = []
        var $tr = $(this).closest('tr');
        var textValue1 = $("input.rate", $tr).val();
        var textValue2 = $('input.quantity', $tr).val();
        amt = textValue1 * textValue2;
        // console.log(amt);
        $('.amount', $tr).html(amt);
        calc_total();
    });

    function calc_total() {
        var sum = 0;
        $(".amount").each(function () {
            sum += parseFloat($(this).text());
        });
        console.log(sum);
        $('#total').text(sum);
    }
</script>


<script type="text/javascript">
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        console.log(newElement);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name')
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        // $("div.form-row.button.is-primary").not(":last").hide();
        // var conditionRow = $('.form-row:not(:last)');
        // conditionRow.find('.button.is-primary')
        // .hide();
        // .removeClass('btn-success').addClass('btn-danger')
        // .removeClass('add-form-row').addClass('remove-form-row')
        // .html('-');
        return false;
    }
    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }
    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('table tr:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

invoice/templates/invoice/invoice-list.html
{% extends 'invoice/base.html' %}
{% block content %}
{% load static %}

<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>
</div>
<form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                All Orders / Change Order Status &nbsp;<button class="button is-rounded is-info">
                    <a href="{% url 'invoice:invoice-create' %}" class="has-text-white">Create Invoice</a></button>
            </p>
        </header>
        <div class="card-content">
            <div class="content">

                <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                    <tbody>
                        <thead>
                            <tr>
                                <th></th>
                                <th>INVOICE</th>
                                <th>CUSTOMER</th>
                                <th>DATE</th>
                                <th>DUE DATE</th>
                                <th>BALANCE</th>
                                <th>TOTAL</th>
                                <th>STATUS</th>
                                <th>View</th>
                                <th>DOWNLOAD</th>

                            </tr>
                        </thead>
                        {% for invoice in invoices %}
                        <tr>
                            <td><input class="checkbox" type="checkbox" value="{{invoice.id}}" name="invoice_id" size="1" />
                            </td>
                            <td width="1%">#{{invoice.id}}</td>
                            <td width="9%">{{invoice.customer}}</td>
                            <td> {{invoice.date}}</td>
                            <td> {{invoice.due_date}} </td>
                            <td width="1%"></td>
                            <td>{{invoice.total_amount}}</td>
                            <td class="level-right">
                                {% if invoice.get_status %}
                                <a class="button is-small is-success" href="#">Paid</a>
                                {% else %}
                                <a class="button is-small is-warning" href="#">Not Paid</a>
                                {% endif %}
                            </td>
                            <td width="1%"><a href="{% url 'invoice:invoice-detail' id=invoice.id %}">
                                <div class="button is-small is-info">View</div>
                            </a></td>
                            <td width="1%"><a href="{% url 'invoice:invoice_pdf' id=invoice.id%}">Download</a></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />
    <div class="card has-background-white-ter">
        <header class="card-header">
            <p class="card-header-title">
                Change Order Status
            </p>
        </header>
        <div class="card-content">
            <div class="select is-rounded">
                <select id="status" name="status">
                    <option value="1">Paid</option>
                    <option value="0">Not Paid</option>
                </select>
            </div>
            <input class="button  is-info is-rounded" type="submit" class="btn" value="Change Status" name="mybtn">
        </div>
    </div>
</form>

{% endblock content %}