Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls')),   
    path('inventory/', include('base.urls')),
    path('invoice', include('invoice.urls')),
    path('inventory/login' , include('invoice.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inventory_list', views.inventory_list, name='inventory_list'),
    path('per_product/<int:pk>', views.per_product, name='per_product'),
    path('add_product/', views.add_products, name='add_product'),
    path('', views.dashboard, name='dashboard'),
]

invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, view_PDF, generate_PDF

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    #path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('invoice_pdf/<id>',generate_PDF, name='invoice_pdf')
]

base/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    cost_per_item = models.DecimalField(max_digits=19, decimal_places=2, null=False, blank=False)
    quantity_in_stock = models.IntegerField(null=False, blank=False)
    quantity_sold = models.IntegerField(null=False, blank=False)
    buying_price = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=False)
    sales = models.DecimalField(max_digits=19, decimal_places=2, null=False, blank=False)
    stock_date = models.DateField(auto_now_add=True)
    last_sales_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=120, unique=True)
    address = models.CharField(max_length=220)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


base/forms.py
from django.forms import ModelForm
from .models import Product

from django import forms

from .models import Product, Supplier


class SupplierForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'name',
        'data-val': 'true',
        'data-val-required': 'Please enter name',
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'address',
        'data-val': 'true',
        'data-val-required': 'Please enter address',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'email',
        'data-val': 'true',
        'data-val-required': 'Please enter email',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'username',
        'data-val': 'true',
        'data-val-required': 'Please enter username',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'password',
        'data-val': 'true',
        'data-val-required': 'Please enter password',
    }))
    retype_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'retype_password',
        'data-val': 'true',
        'data-val-required': 'Please enter retype_password',
    }))

class AddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'sales', 'buying_price','cost_per_item', 'quantity_in_stock', 'quantity_sold']

base/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Supplier, Product
from django.contrib.auth.decorators import login_required
from .forms import SupplierForm, AddProductForm
from django_pandas.io import read_frame
import plotly
import plotly.express as px
import json


# Create your views here.
def inventory_list(request):
    inventories = Product.objects.all()
    df = read_frame(inventories)

    product_in_stock = df.groupby(by="name").sum().sort_values(by="quantity_in_stock")
    product_in_stock = px.pie(product_in_stock, names=product_in_stock.index, values=product_in_stock.quantity_in_stock,
                              title="Product in Stock")
    product_in_stock = json.dumps(product_in_stock, cls=plotly.utils.PlotlyJSONEncoder)
    context = {
        "inventories":inventories,
        "product_in_stock": product_in_stock
    }
    return render(request, 'base/inventory_list.html', context)

@login_required
def per_product(request, pk):
    inventory = get_object_or_404(Product, pk=pk)
    context = {
        'inventory':inventory
    }
    return render(request, 'base/inventory_product.html', context)


from django.views.generic import ListView
from django.contrib.auth.decorators import login_required


# Supplier views
@login_required(login_url='login')
def create_supplier(request):
    forms = SupplierForm()
    if request.method == 'POST':
        forms = SupplierForm(request.POST)
        if forms.is_valid():
            name = forms.cleaned_data['name']
            address = forms.cleaned_data['address']
            email = forms.cleaned_data['email']
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            retype_password = forms.cleaned_data['retype_password']
            if password == retype_password:
                user = User.objects.create_user(username=username, password=password, email=email, is_supplier=True)
                Supplier.objects.create(user=user, name=name, address=address)
                return redirect('supplier-list')
    context = {
        'form': forms
    }
    return render(request, 'store/addSupplier.html', context)


def add_products(request):
    inventories = Product.objects.all()
    inventory_count = inventories.count()
    inventory_quantity = Product.objects.filter(name='')
    if request.method == 'POST':
        form = AddProductForm(request.POST)
        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get('name')
            messages.success(request, f'{product_name} has been added')
            return redirect('dashboard')
    else:
        form = AddProductForm()
    context = {
        'inventories': inventories,
        'form': form,
        'inventory_count': inventory_count,
    }
    return render(request, 'base/inventory_add.html', context)


def dashboard(request):
    inventories = Product.objects.all()
    df = read_frame(inventories)
    
    sales_graph = df.groupby(by="last_sales_date", as_index= False, sort= False)['sales'].sum()
    sales_graph = px.line(sales_graph, x= sales_graph.last_sales_date, y= sales_graph.sales, title="Sales Trend")
    sales_graph = json.dumps(sales_graph, cls= plotly.utils.PlotlyJSONEncoder)
    
    best_perfoming_product = df.groupby(by="name").sum().sort_values(by="quantity_sold")
    best_perfoming_product = px.bar(best_perfoming_product, x=best_perfoming_product.index, y=best_perfoming_product.quantity_sold, title="Best Performing Product")
    best_perfoming_product = json.dumps(best_perfoming_product, cls= plotly.utils.PlotlyJSONEncoder)
    
    product_in_stock = df.groupby(by="name").sum().sort_values(by="quantity_in_stock")
    product_in_stock = px.pie(product_in_stock, names=product_in_stock.index, values=product_in_stock.quantity_in_stock, title="Product in Stock")
    product_in_stock = json.dumps(product_in_stock, cls= plotly.utils.PlotlyJSONEncoder)

    
    
    context = {
        "inventories":inventories,
        "sales_graph":sales_graph,
        "best_perfoming_product":best_perfoming_product,
        "product_in_stock":product_in_stock
    }
    return render(request, "base/dashboard.html", context)

class ProductListView(ListView):
    model = Product
    template_name = 'store/product_list.html'
    context_object_name = 'product'

base/templates/base/addProduct.html
{% extends 'base/base.html' %}

{% block title %}Add Product{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="content-section">
    <form method="POST" >
        <fieldset>
            <legend class="border-bottom pd-2 mb-4 text-center">Add Inventory Form</legend>
            {% csrf_token %}
            <div class="form-group">
                {{ form|crispy }}
            </div>
            <div class="form-group pt-4">

                <button class="btn btn-outline-success" type="submit">Add Inventory</button>
            </div>
        </fieldset>
    </form>
</div>
{% endblock%}

base/templates/base/base.html
<!doctype html>

{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

   <style>
    #weatherWidget .currentDesc {
        color: #ffffff!important;
    }
        .traffic-chart {
            min-height: 335px;
        }
        #flotPie1  {
            height: 150px;
        }
        #flotPie1 td {
            padding:3px;
        }
        #flotPie1 table {
            top: 20px!important;
            right: -10px!important;
        }
        .chart-container {
            display: table;
            min-width: 270px ;
            text-align: left;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        #flotLine5  {
             height: 105px;
        }

        #flotBarChart {
            height: 150px;
        }
        #cellPaiChart{
            height: 160px;
        }

    </style>
</head>

<body>
    <!-- Left Panel -->
    {% include 'base/sidebar.html' %}
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        {% include 'base/navbar.html' %}

        {% block breadcrumbs %}

        {% endblock breadcrumbs %}
        <!-- /#header -->
        <!-- Content -->
        <div class="content">
            <!-- Animated -->
            <div class="animated fadeIn">
                {% block content %}
                {% endblock content %}
            </div>
            <!-- .animated -->
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        {% include 'base/footer.html' %}
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!--  Chart js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

    <!--Chartist Chart-->
    <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="{% static 'assets/js/init/weather-init.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>


    <!--Local Stuff-->
    <script>
        jQuery(document).ready(function($) {
            "use strict";

            // Pie chart flotPie1
            var piedata = [
                { label: "Desktop visits", data: [[1,32]], color: '#5c6bc0'},
                { label: "Tab visits", data: [[1,33]], color: '#ef5350'},
                { label: "Mobile visits", data: [[1,35]], color: '#66bb6a'}
            ];

            $.plot('#flotPie1', piedata, {
                series: {
                    pie: {
                        show: true,
                        radius: 1,
                        innerRadius: 0.65,
                        label: {
                            show: true,
                            radius: 2/3,
                            threshold: 1
                        },
                        stroke: {
                            width: 0
                        }
                    }
                },
                grid: {
                    hoverable: true,
                    clickable: true
                }
            });
            // Pie chart flotPie1  End
            // cellPaiChart
            var cellPaiChart = [
                { label: "Direct Sell", data: [[1,65]], color: '#5b83de'},
                { label: "Channel Sell", data: [[1,35]], color: '#00bfa5'}
            ];
            $.plot('#cellPaiChart', cellPaiChart, {
                series: {
                    pie: {
                        show: true,
                        stroke: {
                            width: 0
                        }
                    }
                },
                legend: {
                    show: false
                },grid: {
                    hoverable: true,
                    clickable: true
                }

            });
            // cellPaiChart End
            // Line Chart  #flotLine5
            var newCust = [[0, 3], [1, 5], [2,4], [3, 7], [4, 9], [5, 3], [6, 6], [7, 4], [8, 10]];

            var plot = $.plot($('#flotLine5'),[{
                data: newCust,
                label: 'New Data Flow',
                color: '#fff'
            }],
            {
                series: {
                    lines: {
                        show: true,
                        lineColor: '#fff',
                        lineWidth: 2
                    },
                    points: {
                        show: true,
                        fill: true,
                        fillColor: "#ffffff",
                        symbol: "circle",
                        radius: 3
                    },
                    shadowSize: 0
                },
                points: {
                    show: true,
                },
                legend: {
                    show: false
                },
                grid: {
                    show: false
                }
            });
            // Line Chart  #flotLine5 End
            // Traffic Chart using chartist
            if ($('#traffic-chart').length) {
                var chart = new Chartist.Line('#traffic-chart', {
                  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                  series: [
                  [0, 18000, 35000,  25000,  22000,  0],
                  [0, 33000, 15000,  20000,  15000,  300],
                  [0, 15000, 28000,  15000,  30000,  5000]
                  ]
              }, {
                  low: 0,
                  showArea: true,
                  showLine: false,
                  showPoint: false,
                  fullWidth: true,
                  axisX: {
                    showGrid: true
                }
            });

                chart.on('draw', function(data) {
                    if(data.type === 'line' || data.type === 'area') {
                        data.element.animate({
                            d: {
                                begin: 2000 * data.index,
                                dur: 2000,
                                from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                                to: data.path.clone().stringify(),
                                easing: Chartist.Svg.Easing.easeOutQuint
                            }
                        });
                    }
                });
            }
            // Traffic Chart using chartist End
            //Traffic chart chart-js
            if ($('#TrafficChart').length) {
                var ctx = document.getElementById( "TrafficChart" );
                ctx.height = 150;
                var myChart = new Chart( ctx, {
                    type: 'line',
                    data: {
                        labels: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul" ],
                        datasets: [
                        {
                            label: "Visit",
                            borderColor: "rgba(4, 73, 203,.09)",
                            borderWidth: "1",
                            backgroundColor: "rgba(4, 73, 203,.5)",
                            data: [ 0, 2900, 5000, 3300, 6000, 3250, 0 ]
                        },
                        {
                            label: "Bounce",
                            borderColor: "rgba(245, 23, 66, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(245, 23, 66,.5)",
                            pointHighlightStroke: "rgba(245, 23, 66,.5)",
                            data: [ 0, 4200, 4500, 1600, 4200, 1500, 4000 ]
                        },
                        {
                            label: "Targeted",
                            borderColor: "rgba(40, 169, 46, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(40, 169, 46, .5)",
                            pointHighlightStroke: "rgba(40, 169, 46,.5)",
                            data: [1000, 5200, 3600, 2600, 4200, 5300, 0 ]
                        }
                        ]
                    },
                    options: {
                        responsive: true,
                        tooltips: {
                            mode: 'index',
                            intersect: false
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        }

                    }
                } );
            }
            //Traffic chart chart-js  End
            // Bar Chart #flotBarChart
            $.plot("#flotBarChart", [{
                data: [[0, 18], [2, 8], [4, 5], [6, 13],[8,5], [10,7],[12,4], [14,6],[16,15], [18, 9],[20,17], [22,7],[24,4], [26,9],[28,11]],
                bars: {
                    show: true,
                    lineWidth: 0,
                    fillColor: '#ffffff8a'
                }
            }], {
                grid: {
                    show: false
                }
            });
            // Bar Chart #flotBarChart End
        });
    </script>
</body>
</html>

base/templates/base/dashboard.html
{% extends 'base/base.html' %}
{% block content  %}

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <h4 class="box-title">Product List </h4>
            </div>
            <div class="card-body--">
                <div class="table-stats order-table ov-h">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th class="serial">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Quantity in Stock</th>
                                <th scope="col">Quantity Sold</th>
                                <th scope="col">Cost per item</th>
                                <th scope="col">Sales or revenue</th>
                                <th scope="col">Stock Date</th>
                                <th scope="col">Last Sales Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for inventory in inventories %}
                            <tr>
                                <td class="serial">{{ forloop.counter }}</td>
                                <th scope="row">{{ inventory.name }}</th>
                                <th scope="row">{{ inventory.quantity_in_stock }}</th>
                                <th scope="row">{{ inventory.quantity_sold }}</th>
                                <th scope="row">{{ inventory.cost_per_item }}</th>
                                <th scope="row">{{ inventory.sales }}</th>
                                <th scope="row">{{ inventory.stock_date }}</th>
                                <th scope="row">{{ inventory.last_sales_date }}</th>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- /.table-stats -->
            </div>
        </div> <!-- /.card -->
    </div>  <!-- /.col-lg-8 -->


</div>


<div class="content-section">
    <div class="row mx-auto justify-content-center">
        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart1"></div>
            </div>
        </div>

        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart2"></div>
            </div>
        </div>
        <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart3"></div>
            </div>
        </div>


    </div>
</div>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script type="text/javascript">
    var graph1 = {{ sales_graph|safe }}
    Plotly.plot("chart1", graph1, {})

    var graph2 = {{ best_perfoming_product|safe }}
    Plotly.plot("chart2", graph2, {})

    var graph3 = {{ product_in_stock|safe }}
    Plotly.plot("chart3", graph3, {})
</script>
{% endblock %}

base/templates/base/footer.html
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                ©Inventory Management System. All Rights Reserved
            </div>
            <div class="col-sm-6 text-right">
                Developed by <a href="https://itsourcecode.com">Elvis Njaramba</a>
            </div>
        </div>
    </div>
</footer>

base/templates/base/index.html
{% extends "base/layout.html" %}
{% block content %}
<h4>Hello World</h4>
{% endblock %}

base/templates/base/inventory_add.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="content-section">
    <form method="POST" >
        <fieldset>
            <legend class="border-bottom pd-2 mb-4 text-center">Add Inventory Form</legend>
            {% csrf_token %}
            <div class="form-group">
                {{ form|crispy }}
            </div>
            <div class="form-group pt-4">
        
                <button class="btn btn-outline-success" type="submit">Add Inventory</button>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

base/templates/base/inventory_list.html
{% extends 'base/base.html' %}
{% block content  %}


<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <h4 class="box-title">Product List </h4>
            </div>
            <div class="card-body--">
                <div class="table-stats order-table ov-h">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th class="serial">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Quantity in Stock</th>
                                <th scope="col">Quantity Sold</th>
                                <th scope="col">Cost per item</th>
                                <th scope="col">Sales or revenue</th>
                                <th scope="col">Stock Date</th>
                                <th scope="col">Last Sales Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for inventory in inventories %}
                            <tr>
                                <td class="serial">{{ forloop.counter }}</td>
                                <th scope="row">{{ inventory.name }}</th>
                                <th scope="row">{{ inventory.quantity_in_stock }}</th>
                                <th scope="row">{{ inventory.quantity_sold }}</th>
                                <th scope="row">{{ inventory.cost_per_item }}</th>
                                <th scope="row">{{ inventory.sales }}</th>
                                <th scope="row">{{ inventory.stock_date }}</th>
                                <th scope="row">{{ inventory.last_sales_date }}</th>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- /.table-stats -->
            </div>
        </div> <!-- /.card -->
    </div>  <!-- /.col-lg-8 -->


</div>
<div class="content-section">
 <div class="card m-4" style="width:90%;">
            <div class="card-body">
                <div id="chart3"></div>
            </div>
        </div>
</div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script type="text/javascript">
    var graph3 = {{ product_in_stock|safe }}
    Plotly.plot("chart3", graph3, {})
</script>
{% endblock %}

base/templates/base/sidebar.html
<aside id="left-panel" class="left-panel" style="background: black">
    <nav class="navbar navbar-expand-sm navbar-default" style="background: black">
        <div id="main-menu" class="main-menu collapse navbar-collapse" style="background: black">
            <ul class="nav navbar-nav">
                <li class="active" style="background: black" >
                    <a href="{% url 'dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>
                <li class="menu-title" style="color: white">My Store</li><!-- /.menu-title -->

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-list"></i>Product</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'add_product' %}">Add</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'inventory_list' %}">View</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-shopping-cart"></i>Order</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="">Add</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="">View</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-shopping-cart"></i>Invoice</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'invoice:invoice-create' %}">Add</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'invoice:invoice-list' %}">View</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>